### Conditionals
Python is indentation based which means there are no brackets or braces for conditionals.
- Semicolons are used to mark the end of the condition. 
- Else if is done using the keyword `elif`
- Parenthesis can be added around the condition but are not required
- Conditionals can also be used as an expression in a similar way that the ternary operator works in C-style languages
	- `my_var = "yes" if bool(x) else "false"`
	- There is no ternary operator in Python because of this

```python
# Normal conditional. Indetation important!
var = 5
if var > 10:
	print("your var is over 10")
elif var < 10:
	print("your var is under 10")
else:
	print("your var is 10")

# Conditional expression
var = 5
sign = "positive" if var >= 0 else "negative"

# Can have chained conditional expressions, but it's bad style
# This does the same as the normal conditonal above
var = 5
string = "over 10" if var > 10 else "under 10" if var < 10 else "10"
print(f"your var is {string}")
```

### Loops
In Python, all for loops iterate over lists/iterables without exception. The behavior of a numerical only for loop can be easily achieved though
- About `range`:
	- `range(x)` - Returns an iterable of numbers from zero up to the given number
		- The iterable excludes `x`
		- So `x` could be the length of a list, for example
	- `range(x, y)` - Returns an iterable of numbers from `x` to `y`, excluding `y`
	- `range(x, y, s)` - Returns an iterable of numbers from `x` to `y`, excluding `y` with a step of `s`
- `enumerate(li)` - Returns an iterable that retrieves both the list element and it's index
- `break` and `continue` work as they do in other programming languages
	- `break` exits loop processing
	- `continue` immediately starts the next iteration of the loop

```python
# Prints 01234
for i in range(5):
	print(i, end='')

# Prints 56789
# Cannot put parenthesis around full loop, only clause after 'in'
for i in (range(5, 10)):
	print(i, end='')

# Prints 13579
for i in range(1, 10, 2):
	print(i, end='')

# Loop over list
for i in ["one", "two", "three"]:
	print(i)

# Loop over list to get element and index
pets = ["dog", "cat", "fish"]
for i, val in enumerate(pets):
	print(f'Pet ranking {i + 1}: {val}')
```

While loops in Python aren't all that different from other languages, just use Python syntax
```python
x = 0
while x < 5:
	print(x)
	x += 1
```

### Iterables and Iterators
Python has a special type of object called an Iterable. It can be treated like a sequence and is what can be used in loops. Cases of iterables include the return of the `range`, `dict.values()`, and `dict.keys()` methods. 
- Under the hood, an iterable is any Python object with an `__iter__()` method. So it is possible to create your own iterable object
- Iterables can be looped over, but accessing specific elements via their index is impossible
	- Will raise a TypeError
- Can use an *iterable* to create an *iterator*

Iterators in Python are special objects that can not only be looped over, but can remember their state as they are traversed through
- Like with an iterable, and iterator under the hood is an object with an `__iter__()` method, but it also must have a `__next__()` method

To retrieve all elements from an iterable or iterator, make a call to `list()` 
- This creates a list with all elements from the iterable / iterator

```python
my_dict = {"one": 1, "two": 2, "three": 3}
my_iterable = my_dict.keys()

# Can loop over the iterable
for i in my_iterable:
	print(i)

# Can make it into an iterator
my_iterator = iter(my_iterable)
next(my_iterator) # prints first value ("one")
next(my_iterator) # "two"
next(my_iterator) # "three"
next(my_iterator) # No more data, raises StopIteraton
# Yes it's StopIterator, not StopIteratonError or similar

# Can also loop over the iterator
# Loop will pick up where calls to next(my_iterator) left off
my_iterator_2 = iter(my_iterable)
print(next(my_iterator_2)) # Prints "one"
# Prints "two" and "three"
for i in iter(my_iterable_2):
	print(i)
```

### Exceptions
- Exceptions in Python are handled with a try-except block (similar to try-catch)
- To raise and exception, do `raise ExceptionName`
- Multiple exceptions can be caught in one block, and they do not need to be assigned to a variable
- Unlike some languages, an `else` block can be added to only run when an exception is *not* raised
- The finally block will execute after all other code, as a finally block usually does
```python
try:
	raise IndexError("This is an error")
except IndexError as e:
	print(f"There was an error: {str(e)}")
except (TypeError, NameError):
	pass
else:
	print("No exceptions thrown!")
finally:
	print("clean up resources")
```

>Pass
>
>The `pass` keyword is used as a placeholder for when a code block isn't allowed to be empty. It should not be used in production, but is more of a TODO placeholder to not cause any errors during development. It does nothing and allows code to continue executing.

To print the stack trace of an exception, import the `traceback` module and use `traceback.print_exec()`

A full list of Python errors/exceptions can be found [here](https://docs.python.org/3/library/exceptions.html), but here are some common ones:
- `SyntaxError` - Interpreter encounters a syntax error
- `TypeError` - A function or operation is applied to an object / variable of the wrong type
- `ValueError` - A function or operation gets an argument of correct type but wrong value
- `IndentationError` - Incorrect indentation in the code
- `NameError` - A variable name is not found in local or global scope
- `KeyError` - A key is not found in a dictionary
- `IndexError` - An index of a sequence is out of range
- `ImportError` - Interpreter cannot find the imported module
- `OSError` - A system operation caused a system related error
- `RuntimeError` - Raised when an error does not fall into a pre-existing category